// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConversation() {
  return window['go']['main']['App']['CreateConversation']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function StopGeneration() {
  return window['go']['main']['App']['StopGeneration']();
}
