// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConversation():Promise<string>;

export function DeleteConversation(arg1:string):Promise<void>;

export function GetConversation(arg1:string):Promise<string>;

export function GetConversations():Promise<string>;

export function RenameConversation(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StopGeneration():Promise<void>;
